### ISSUE TITLE
witch flutter version

### ISSUE THREAD

**Issue by 6543** [bauerj/paperless_app#11]
@bauerj witch flutter version do you use?

**Comment by 6543** [comment]
ok v1.17.3 worked - would still be nice to add a hint to readme throu ...

**Comment by bauerj** [comment]
Thanks for letting me know, I will add that information to the Readme.

Did you try with a newer version and it didn't work?

**Comment by bauerj** [comment]
I just tested it with Fluuter 1.20.4. It failed to build because one of the dependencies was not compatible. I upgraded the dependencies and now it should work with all recent Flutter versions again. Sorry for the confusion

**Comment by amenk** [comment]
I have problems with 2.2.0 now -- can you still add the used flutter version to the readme (or to the pubspec?)
