### ISSUE TITLE
Problems with Let's Encrypt certificate

### ISSUE THREAD

**Issue by virdb** [bauerj/paperless_app#14]
Error while connecting to server

DioError [DioErrorType.DEFAULT]:
HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

**Comment by bauerj** [comment]
This might be a configuration error on your side. Can you do a test using https://www.ssllabs.com/ssltest/?

It should show something like "Chain issues: incomplete".

**Comment by virdb** [comment]
You were right, now it's fixed
thanks a lot

**Comment by bauerj** [comment]
You're welcome! Thanks for testing the app and let me know if there are any other issues or feedback.

**Comment by sohnemann** [comment]
Hi there,

I get the same error , but with my own certificate instead.
I created a CA-certificate with mkcert and added it to my device's truststores. Is there any possibility to make this scenario work?

Cheers,
sohnemann

**Comment by bauerj** [comment]
Hey sohnemann,

I would have expected that to work. I assume you can access the URL with your browser but not with the Paperless app? 

I could add the possibility to manually accept self-signed certificates within the app but of course it would be better if the OS-level mechanisms could be used.
