### ISSUE TITLE
Connection error popup remains after retry

### ISSUE THREAD

**Issue by mvdkleijn** [bauerj/paperless_app#15]
Hi,

Not a biggie since there's an easy workaround, more of a beauty thing but I thought I'd mention it.

When you start the Paperless app and it cannot connect to the server, a pop-up appears that allows you to edit the settings or retry.

(I accidentally had the server shutdown when opening your app)

After starting the server and hitting retry in the app, the connection is successfully established but the pop-up remains.

The workaround is simple: close the app en reopen.

Thanks for the app! :smile:

**Comment by bauerj** [comment]
Thanks, that should be easy enough to fix.
