### ISSUE TITLE
Offer Android form filling for username and password

### ISSUE THREAD

**Issue by Whisprin** [bauerj/paperless_app#21]
Hello,

I'm using a password manager on Android which is using the Android Autofill framework to fill passwords and usernames.

However, during the login dialogue of this app the password manager autofill option is not available. Maybe the form fields are missing a flag?

This is how it should look like: [KeePassDX Form filling](https://raw.githubusercontent.com/Kunzisoft/KeePassDX/master/fastlane/metadata/android/en-US/images/phoneScreenshots/screen2.jpg)

**Comment by bauerj** [comment]
Yes, you're right. This feature has been added to Flutter after I started developing the login form so I wasn't aware it exists.

But it does and I will add it in the next release 🎉

**Comment by bauerj** [comment]
Thanks @Whisprin,

this will be part of the next release which I assume will be this weekend.
