### ISSUE TITLE
Can't connect with http url

### ISSUE THREAD

**Issue by oresk** [bauerj/paperless_app#28]
I have a paperless-ng instance on a local network and I do not have ssl setup for it. It is not available on the internet and if I need to connect to it from outside I can connect to the network through a vpn. 

I am getting a Insecure HTTP is not allowed by platform error.

**Comment by bauerj** [comment]
Okay, it seems like Android and iOS disable plaintext connections by default: https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android

There are some security implications to this, even if you assume your home network is secure. If you open the app in a different network (by accident) you could leak your credentials to anyone in that network.

But I guess we should enable HTTP for the app and show a warning message when anyone tries to connect to a server without HTTPS. This seems easy enough to do (outlined in the link above) but I don't have time until after Christmas. If anyone else wants to tackle this, please go ahead.

**Comment by qcasey** [comment]
I'm also seeing this when using http. I'll put together a fix later today.

**Comment by oresk** [comment]
I can test it when it is ready. Ping me if there is need for that.

**Comment by qcasey** [comment]
@oresk The latest 0.0.9 release on Google Play should have fixed this issue. Please let us know if you're seeing the same :smiley:

**Comment by oresk** [comment]
Working now! \o/

Thnx, everybody for your work!
