### ISSUE TITLE
Squished/narrow image when capturing new document.

### ISSUE THREAD

**Issue by CorneliousJD** [bauerj/paperless_app#31]
This was the result of the Google app store review where you asked me to submit the issue.

Here's an example photo, along with a screenshot for how squished it looks in the app.
Note that once I select the bounding box around the document and actually OK it, the dimensions are corrected.

ACTUAL: 
![image](https://user-images.githubusercontent.com/724777/103241599-b5561c80-4921-11eb-995e-25848c78b1ac.png)

APP: 
![image](https://user-images.githubusercontent.com/724777/103241606-ba1ad080-4921-11eb-8f12-d6a485e45e5a.png)

**Comment by bauerj** [comment]
Thanks for your screenshots.

Sadly the upstream library that contains this bug (https://github.com/sawankumarbundelkhandi/edge_detection) seems to be unmaintained. However, there are two outstanding pull requests, one of which seems to fix this issue (and also the annoying issue with the triangle you are seeing).

I will merge both PRs into my fork and see if this helps.

**Comment by CorneliousJD** [comment]
Sounds good - overall it works just fine - the weird triangle also fixes itself when sitting on the doc long enough, more of a visual glitch than a usability one, but if you need any help testing let me know, thanks!

**Comment by bauerj** [comment]
Okay, my build environment broke for no apparent reason but now I have a version with the changes integrated:
https://bauerj.eu/app-arm64-v8a-release.apk

Can you try this release candidate and see if it fixes the issue?

**Comment by CorneliousJD** [comment]
Tested. That seems to work! I do still get the weird triangle bounding box sometimes but it wasn't ever much of an issue before either. :) 

No more squish thought! Thanks!

**Comment by bauerj** [comment]
Wow, that was quick! I'm glad it works now.

Thanks a lot to @vmwsree and @tiagosito for your work on the edge detection library!

I will release an update with all the improvements to the scanner soon.

**Comment by bauerj** [comment]
Okay, this is fixed in 0.0.10 which should be available through Google Play on Wednesday.
