### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [bauerj/paperless_app#37]
https://f-droid.org/wiki/index.php?title=eu.bauerj.paperless_app/lastbuild_11&oldid=288502

We use https://github.com/bauerj/paperless_app/blob/master/pubspec.yaml#L14 to get the new version, but if you just bump this without tagging F-Droid can't actually build.

ReF: https://gitlab.com/fdroid/fdroiddata/-/commit/047ecb5049abb37a44748f17ba9400aaae769b08

**Comment by bauerj** [comment]
Hey,

thank you for bringing this to our attention. 0.0.11 is not ready yet, which is why I didn't tag it. Would it be easier for you if I only update the version string when also tagging a new version?

**Comment by licaon-kter** [comment]
Yes, ideally you'd bump version and tag that commit

**Comment by OliveiraHermogenes** [comment]
It seems that there is a tag for 0.0.11, but I'm missing the F-Droid build. Maybe something went wrong?

**Comment by bauerj** [comment]
My understanding is that .11 will not be built by F-Droid due to the mistake I made. The next version should hopefully work.
