### ISSUE TITLE
FR, Scan from Phone Gallery

### ISSUE THREAD

**Issue by MatyasK** [bauerj/paperless_app#39]
It would be usefull if we can pick an already existing image from the gallery and upload it.

I will start working in this feature, and submit a PR if I have a working version!

**Comment by bauerj** [comment]
Hey 👋

Thanks for your feature request. 

Hold your horses please. As far as I understand that already works:


https://user-images.githubusercontent.com/598790/113133402-e5ae9f00-921f-11eb-86f9-9526c9d4f564.mp4

Is that broken for you? Or did you mean something else?

**Comment by MatyasK** [comment]
hey,
I didn't know this exists amazing work:), but I was thinking to have this option within the application UI.

I'm also a flutter developer, I will send you DM maybe I can help with the application :)

**Comment by bauerj** [comment]
Ah, I see! This feature had been added by @qcasey so I direct all compliments to him 😄

You're right though, it would make sense to also have this in the app. Users could choose between scanning or picking from gallery when clicking the floating action button. If you would like to contribute that it would be much appreciated!

Also feel free to message me on telegram (@ bauerj) or by email (paperless_app@bauerj.eu).

**Comment by bauerj** [comment]
This has been implemented by @MatyasK now 🎉
