### ISSUE TITLE
App is shown as "paperless_app" in recently used apps

### ISSUE THREAD

**Issue by totti4ever** [bauerj/paperless_app#4]
No clue, if this is a quick win, just wanted to let you know

**Comment by bauerj** [comment]
Thanks for reporting this. This is the first feedback I got for this app! 

Indeed, it's quite annoying that it shows up like this. I actually fixed this already but forgot to release an update to the Play Store. I will do so later.

**Comment by totti4ever** [comment]
> Thanks for reporting this. This is the first feedback I got for this app!
Great, I'm glad somebody started an app! I think it's not that easy to find in the store though, no clue what to improve since the paperless main app is named the way it is...
So including this in the docs/readme there as you proposed is the right thing to do, I guess

**Comment by bauerj** [comment]
It's currently only visible through the link in the README because it's still in beta. Once enough users have tested it I will make it more accessible.
