### ISSUE TITLE
Document date is wrong, probable timezone issue

### ISSUE THREAD

**Issue by amenk** [bauerj/paperless_app#45]
**Describe the bug**
The date of the document is not matching the date displayed in the app.

**To Reproduce**
1. Paperless Server runs in timezone Europe/Berlin
2. Scan a document dated 1.3.2021
3. View the document in the paperless app
4. Date Feburary 28, 2021 is displayed

**Expected behavior**
The date is viewed as March 1, 2021

**Screenshots**

Paperless-ng server:

![ksnip_tmp_pXkOPl](https://user-images.githubusercontent.com/1087128/115985304-90aa4280-a5ab-11eb-86db-3664e5b5f8d3.png)

App:

![image](https://user-images.githubusercontent.com/1087128/115985363-dc5cec00-a5ab-11eb-9cb0-9bc3ff76fda8.png)

**Additional information**
*Paperless App Version*: 0.0.10, f-droid
*Do you use Paperless NG as a backend*: Paperless-ng 1.4.1

**Possible cause**

It might be because the display timezone is different in the app and the server. Can the app query the server timezone? In the end of the time it's only dates, not date time, so I am not sure if any timezone logic has to take place.

**Comment by jonaswinkler** [comment]
Did you configure `PAPERLESS_TIME_ZONE` properly?

**Comment by amenk** [comment]
Yes it's set to Europe/Berlin on the paperless docker env

**Comment by amenk** [comment]
If I do not set this variable and use the UTC default, it works.

**Comment by bauerj** [comment]
I can reproduce this issue here.

The timestamp comes back from the server as 2021-02-28T23:00:00Z which would be correct for Europe/Berlin. The app currently displays the timestamp in UTC, not the local timezone.

I will change the app behaviour to be consistent with the web interface. However, I'm not sure if this is really what the user expects. If I scan a document in March at home, then travel to London, I don't expect it to show up in February.

**Comment by amenk** [comment]
Yeah, time zones are tough and are a headache.

So it would take the time zone from the server? If the sever stays at home it might still show march.

Frequent travelers just should run the sever in UTC ;-) ?

**Comment by bauerj** [comment]
> So it would take the time zone from the server?

No, the local time zone from the OS. Changing the server to UTC just fixed the issue because the app currently assumes the date should be displayed in UTC.
