### ISSUE TITLE
TLSv1.0 as maximum by dio package ?

### ISSUE THREAD

**Issue by jsievertde** [bauerj/paperless_app#47]
**Describe the bug**
As I connect to my paperless-ng Server I get the error that Dio can't connect to the server.
Webserver works without problems.
**To Reproduce**
1. Go to server selection page on first use
2. Enter a server that only supports TLSv1.3
3. Try to connect to the Server

**Expected behavior**
The app connects to the server

**Screenshots**
![image](https://user-images.githubusercontent.com/16487382/120366713-46d21c00-c310-11eb-88e0-6f76f9010285.png)

**Additional information**
*Paperless App Version*: e.g. 0.0.10
*Do you use Paperless NG as a backend*: (Yes/No)

**Comment by bauerj** [comment]
Hey,

I can't reproduce this with 0.0.11. Could you please update and let me know if this resolves your issue?

**Comment by bauerj** [comment]
@jsievertde Did you have time to test with 0.0.11 yet?

**Comment by jsievertde** [comment]
@bauerj 

sorry for the long wait.
It does work in 0.0.11
I just installed from the release page manually as f-droid is still on 0.0.10

**Comment by bauerj** [comment]
Oh right, sorry about that! It should be fixed with 0.0.12.

And thanks for testing again!

**Comment by jsievertde** [comment]
thanks for your work on this app makes it easier to use less paper for archiving.
