### ISSUE TITLE
Error while connecting to server: Http status error [200]

### ISSUE THREAD

**Issue by philbradley** [bauerj/paperless_app#51]
Paperless-ng is running on a host on the local lan, behind a reverse proxy (caddy v2).  The address is in the format https://abc.example.org/scan/ . The router (openwrt, running dnsmasq) has been set up to return the host's LAN IP, rather than an external IP, for abc.example.org .

I can connect through the browser on several devices.

I can also successfully login to the API using HTTP basic auth (curl --user USERNAME https://abc.example.org/scan/api/documents/) from a local PC.

I can also successfully login via the (separate) Android "Paperless Share" app.  This works fine.

If I point the "Paperless" app (also on Android) to https://abc.example.org/scan/ , when connected to the same local WiFi, I get prompted for username and password, but then get told: 

> Error while connecting to server
> DioError [DioErrorType.RESPONSE]:
> Http status error [200]

I get this whatever username and password I put in - correct ones, false ones, etc.

*Paperless App Version*: 0.0.11

**Comment by qcasey** [comment]
Thank you for the detailed report! 

I'm on mobile now, but I think this has to do with the validation that determines which paperless server to use. 

https://github.com/bauerj/paperless_app/blob/a72fc4effc7515f09ff972a108e6b60f1572411f/lib/api.dart#L230

I'll help with this once I'm back at the desk.

**Comment by qcasey** [comment]
Could you share your reverse proxy directive?

**Comment by philbradley** [comment]
Sure thing.  The relevant part of the Caddyfile is as follows:

```
abc.example.org {
reverse_proxy /* someotherphotohostingservice:2342
reverse_proxy /scan/* paperless_webserver_1:8000
reverse_proxy /rss/* http://rssaggregator-docker_web-nginx_1
}
```
This configuration makes Caddy automatically get an SSL certificate from Let's Encrypt for the domain (which is not actually abc.example.org, of course).

The other thing to note is that the paperless-ng postgres database is running on a nonstandard port (I was getting weird authentication errors when it was running on the same port as the postgres container for my self-hosted RSS aggregator.  At some point I might make them use the same postgres instance, but for now they're distinct containers on distinct ports.  

So my docker-compose.env is:
`PAPERLESS_FORCE_SCRIPT_NAME=/scan
PAPERLESS_DBPORT=5430
`

And the relevant part of my docker-compose.yml is:
`
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperlessuser
      POSTGRES_PASSWORD: paperlesspassword
      command: -p 5430
`

**Comment by qcasey** [comment]
That's excellent, thanks. I was trying all kinds of `url rewrite` and `header` tricks when ```PAPERLESS_FORCE_SCRIPT_NAME=/scan``` is what I needed to get it working.

I'm seeing the same error you are when there's a trailing slash in the URL field.

* `https://abc.example.org/scan/` fails while
* `https://abc.example.org/scan` logs in correctly

This is a bug in how `baseURL` is handled, I'll create a PR later to fix this so either variation of the above should work.

When you get a min, could you confirm if dropping the trailing slash works for you?

**Comment by philbradley** [comment]
Dropping the slash works perfectly.  The app must be adding the slash back in before making a connection attempt, because /scan is not a valid paperless-ng address on my server - it gets handled under my reverse proxy's _/*_ redirect rule.

**Comment by philbradley** [comment]
I can understand why it would do so, because the Paperless-NG documentation instructs you to leave out the trailing slash when hosting at a subpath ("_To host paperless under a subpath url like example.com/paperless you set this value to /paperless. No trailing slash!_") .  That's what I've done in the paperless-ng config, but my Caddyfile redirect _does_ include the trailing slash (omitting it didn't seem to work).  Maybe it should check whether the baseURL includes a trailing slash, and only include one if it's missing?

**Comment by qcasey** [comment]
IIRC an nginx proxy requires the same thing to work also, no big deal :)

 This fix will be included in the next release. Thanks for your help!
