### ISSUE TITLE
Feature Request: Filter by correspondents and tags

### ISSUE THREAD

**Issue by totti4ever** [bauerj/paperless_app#6]
eventually the same as the right side bar in the web ui

**Comment by bauerj** [comment]
Would it make sense to you if the search would list matching recipients/tags first and by clicking on it, the list would filter accordingly?

**Comment by totti4ever** [comment]
Yes, I think for the normal use case this would be absolutely enough and helpful. Going through existing tags/corr. should be an advanced and other use case

**Comment by bauerj** [comment]
This has now been implemented in the latest beta release.
