### ISSUE TITLE
Error while connecting to server (old (legacy) server and  app v. 0.1.0)

### ISSUE THREAD

**Issue by OliveiraHermogenes** [bauerj/paperless_app#62]
**Describe the bug**
After upgrading to version 0.1.0 (F-Droid), I am getting the following error upon trying to log in:

```
Error while connecting to server

type '_GrowableList<dynamic>' is not a subtype of type 'Iterable<String>' in type cast

```
If it is relevant, I have not yet migrated to Jonas' -NG (didn't work too well for me last time I tried), so I am still running the old paperless from Daniel. 

**Additional information**
*OS*: LineageOS 17.1 (Android 10)
*Paperless App Version*: 0.1.0
*Do you use Paperless NG as a backend*: No

**Comment by bauerj** [comment]
Hey,

yes, the new app version wasn't tested with the old version of paperless. Sorry about that!

I'll see if I can fix it for the next minor release. This is going to take a few days though, so please try to downgrade in the meantime.

I'll have to see what I can do so that only stable releases get uploaded to F-Droid.

**Comment by bauerj** [comment]
I think I may have fixed this now. Could you please try if  [app-arm64-v8a-release.zip](https://github.com/bauerj/paperless_app/files/8035795/app-arm64-v8a-release.zip) works for you?

**Comment by bauerj** [comment]
No worries, that's my bad for assuming everyone uses a new device 😉

[app-armeabi-v7a-release.zip](https://github.com/bauerj/paperless_app/files/8040943/app-armeabi-v7a-release.zip) - this should work on your phone.

If you have an old paperless instance running without any personal or sensitve data on it, I would be happy if you gave me access for future testing. If it's your personal instance where you store your own data, I would not want to access it.
