### ISSUE TITLE
save sorting

### ISSUE THREAD

**Issue by fleixi** [bauerj/paperless_app#68]
Every time the app gets closed Form androids memory manager the sorting is reset to default.

Since i always need "date added" this is annoying.

please save the sorting or make it possible to select a custom default in the settings.

**Comment by bauerj** [comment]
Thanks for reporting this!

I use the default sorting so I didn't notice that. I agree that that would be very annoying. I will come up with a fix soon.

**Comment by bauerj** [comment]
Hey @fleixi,

I have fixed this in 7d00cb6. It will be part of the next update which should come soon.

**Comment by bauerj** [comment]
This is now fixed in 0.1.2.
