### ISSUE TITLE
translation not working

### ISSUE THREAD

**Issue by fleixi** [bauerj/paperless_app#69]
I using the app in a german Android 11 Lineageos but the app is in english.

Is the translation from crowdin not implementet or is this a bug.

Im using the fdroid version 0.1.1

**Comment by bauerj** [comment]
Thanks for reporting this.

Indeed, there is a step missing in the current F-Droid build.

My current plan is to bring out a new version soon, then immediately change the metadata on F-Droid myself and hopefully we should have a translated version available then!

**Comment by bauerj** [comment]
Okay, everything has been set into motion: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10669

Let's see how this works out!

**Comment by bauerj** [comment]
@fleixi can you check whether the new version has translations now?

**Comment by fleixi** [comment]
The new version is not be avaible since now, i will check it as sone as possible

**Comment by fleixi** [comment]
It is working now thx
