### ISSUE TITLE
Alternative download

### ISSUE THREAD

**Issue by IzzySoft** [bauerj/paperless_app#8]
Are there plans to make the APK available outside of Play Store (for people not having access to that) – e.g. by attaching it to your `releases/`, or even bringing it to [F-Droid](https://f-droid.org/)?

One side-question: what for is the `REQUEST_INSTALL_PACKAGES` permission needed here?

**Comment by bauerj** [comment]
Indeed, it would be nice to have another distribution channel available. I already looked into F-Droid but could just get their toolchain running. Any help would be appreciated.

For now, I have uploaded the release APKs to the releases here, as per your suggestion.

**Comment by bauerj** [comment]
Oh, and with regards to your second question: Where exactly do you see this? As far as I know the app only uses `android.permission.INTERNET`.

**Comment by IzzySoft** [comment]
The [Exodus report](https://reports.exodus-privacy.eu.org/en/reports/130530/) for the current version shows `INTERNET`, `READ_EXTERNAL_STORAGE` and `REQUEST_INSTALL_PACKAGES` being requested by the app. And using `aapt` on the APK confirms that.

As for F-Droid inclusion: I gladly assist with that (disclosure: I'm one of the maintainers). I'd suggest starting by implementing [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo here (details & reasons behind the link). Having that done & tagged, simply [open an RFP](https://gitlab.com/fdroid/rfp/issues) (please also specify there if your license is GPL-3.0-only or GPL-3.0-or-later). If it's possible, also make [versionCode and versionName](https://github.com/bauerj/paperless_app/blob/master/android/app/build.gradle#L49) literal values (the update checker and the build service need that). If for some reason that's not possible, please say so (and point out we shall use HTTP check on [pubspec.yaml`](https://github.com/bauerj/paperless_app/blob/master/pubspec.yaml) instead; that's not as good, but should work as well). I'll pickup from there then.

Thanks to your adding the APKs to releases, I've sped things up a bit and added your app to my repo – so it will [show up here](https://apt.izzysoft.de/fdroid/index/apk/eu.bauerj.paperless_app) with the next sync in about 20h. Once your app got listed at F-Droid, I'd remove it again at my end (mainly to avoid confusion due to different signatures, as F-Droid signs with its own key) – unless you wish it to stay because of "faster updates and having a fallback" :wink:

Big thanks!

**Comment by bauerj** [comment]
Thank you for outlining the process, that's really helpful!

I have a few questions if you don't mind:

* The APKs for the different architectures have different version codes (1001, 2001, ...) for the same version. Do I need to copy the changelog file for each architecture or is there a simpler method?
* Do you want me to change `versionCode flutterVersionCode.toInteger()` to `versionCode flutterVersionCode` in app/build.gradle?

Once I tag a new release I will open a RFP with F-Droid and mention you there.

I also found out where the other permissions `READ_EXTERNAL_STORAGE` and `REQUEST_INSTALL_PACKAGES` come from. It's the [open_file](https://pub.dev/packages/open_file) package, which is used to open PDF files. Since neither permission seems to be needed, I'll try and remove these from the app.

**Comment by bauerj** [comment]
Apparently changing `versionCode flutterVersionCode.toInteger()` to `versionCode flutterVersionCode` is not the right thing to do as it makes the build fail.

**Comment by IzzySoft** [comment]
I honestly have no idea how to deal with multiple versionCodes on release. If you can place files for each, that should certainly work (let me know once you did so I already activate that for my repo). We can ask that in the RFP, addressing our packagers.

And no, "literal" means literal, so I meant rather `versionCode 5` and `versionName '0.0.5'`. As I wrote, we could perform the update check on the `pubspec.yaml` (which has both values as literals). But somehow `build.gradle` is preferred :wink:

Good you found the cause for the two "hidden permissions"! And even better you removed the unneeded ones :smile: Especially `REQUEST_INSTALL_PACKAGES` as it always at least raises an eyebrow (if not suspicions).

I see you've already started on Fastlane, great! A little hint: in `full_description.txt` you can use "basic HTML" for formatting. Checking yours, interesting ones will be p,ul,li, a href – maybe also b,i (though on a quick glance I spotted no attempt on them).

**Comment by bauerj** [comment]
> We can ask that in the RFP, addressing our packagers.

Okay, I will do that!

> And no, "literal" means literal, so I meant rather `versionCode 5` and `versionName '0.0.5'`.

I would prefer not to do that as it seems like something I would definitely forget while releasing a new version. IMO it would be better if that would all be defined in the pubspec.yaml.

> I see you've already started on Fastlane, great! A little hint: in full_description.txt you can use "basic HTML" for formatting

Sure, that makes sense, especially for the lists.

**Comment by IzzySoft** [comment]
Yupp, fits – thanks!

**Comment by 6543** [comment]
[!7304](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7304) got merged

**Comment by bauerj** [comment]
Thanks @IzzySoft and @6543!

**Comment by bauerj** [comment]
When should I expect it to be available through F-Droid? I can't seem to find it yet.

**Comment by 6543** [comment]
2-7days (it has to be build and the signed)
